### ISSUE TITLE
Erro no texto | Sobre nós

### ISSUE THREAD

**Issue by bpires** [Kayke-Fujinaka/LemonPepper#1]
Fala Kayke,

Verifiquei um erro no texto da seção "Sobre nós":

>A gente ama o que faz e sabe que o brasileiro é apaixonado por pizzas. Por isso, nossa missão é vender pizza com mais diversão. A ~~Domino’s Brasil~~ **LemonPepper** é uma empresa que integra o seleto grupo das melhores empresas para se trabalhar, segundo a Mente do Kayke (MK).

Corrige lá! Parabéns pela ideia da adaptação, achei fantástica!!!

**Comment by Kayke-Fujinaka** [comment]
Corrigido :)
